refactor: Chipコンポーネントのデザイン調整
3-shake/3design-ui pull request #610
Opened 2022-05-20 11:47 UTC by O-natsu

### monday

- Chipコンポーネントのデザインと実装に差異がある

### preview

|before|after|
--- | ---
|<img width="208" alt="スクリーンショット 0004-05-20 20 30 15" src="https://user-images.githubusercontent.com/44659317/169521781-a3d60d86-4087-4a33-9fd6-46b6368f61c7.png">|<img width="269" alt="スクリーンショット 0004-05-20 20 46 54" src="https://user-images.githubusercontent.com/44659317/169521924-53ed0a98-3063-446c-96aa-528e6ca2a532.png">|

<img width="400" alt="スクリーンショット 0004-05-20 20 44 52" src="https://user-images.githubusercontent.com/44659317/169521864-5dc7ac5a-149c-433b-889f-a9c5f7f74e5c.png">

### 実装内容
- colorでnegativeを選択した場合に背景色しか変更されないので現行デザインと合わせた

### 相談内容(あれば)
- colorTypeの追加があればください〜 🙏

2022-05-20 11:48 UTC, O-natsu commented on src/chip/Chip.tsx
> +              ${tw`opacity-70`}
@Qs-F ここのcolorがなかったのでイケてないんですが一旦opacity下げてみました 🙇

2022-05-20 11:49 UTC, O-natsu commented on src/chip/Chip.tsx
> +              ${tw`opacity-70`}
他のカラバリ欲しいのあればついでに追加しちゃおうと思います

2022-05-20 11:51 UTC, Qs-F commented on src/chip/Chip.tsx
> +              ${tw`opacity-70`}
> ここのcolorがなかったのでイケてないんですが一旦opacity下げてみました 🙇

了解です！

2022-05-20 11:59 UTC, Qs-F requested changes
ありがとうございます！！

これは相談なんですが、IconのAPIをもしできたらデザイン側に合わせてpropsの `icon` -> `leadingIcon`, `deleteIcon` -> `trailingIcon` にしたいのですが、これやると今後メンテ大変ですかね… 🤔

2022-05-20 11:59 UTC, Qs-F commented on src/chip/Chip.tsx
> +function styles(color: ColorType) {
```suggestion
const styles = (color: ColorType) => {
```

他と合わせるならこうですかね？なにか理由があるのかもなのでおまかせします！

2022-05-20 11:59 UTC, Qs-F commented on src/chip/Chip.tsx
> +              ${tw`opacity-70`}
positiveとnoticeは一旦サービス固有にしておきたいので、whiteを追加できたらほしいです！

スタイルはvariant = outlinedを上書きする感じですかね

2022-05-20 12:18 UTC, O-natsu commented
@Qs-F 
> propsの icon -> leadingIcon, deleteIcon -> trailingIcon にしたいのですが、これやると今後メンテ大変ですかね… 🤔
これってつまり
```
type ChipProps = exclude<MuiChipProps, 'color'> & {
...
leadingIcon: MuiChipProps['icon'],
trailingIcon: MuiChipProps['deleteIcon']
}
```
こうしたいってことで合ってますかね…？
個人的には、MUIのバージョン上げた際、Propsに破壊的変更入ってたらここも影響しちゃうなあ…という懸念があります。。。

2022-05-20 12:23 UTC, Qs-F commented
@O-natsu そうです！自分もそう思ったんですが、その変更入ると結局サービス側で修正入れなきゃいけなくて、だったら3design-ui側で抽象化しておくのもありかな…思ったんですがいかがでしょう？

2022-05-20 12:28 UTC, O-natsu commented
@Qs-F なるほど。逆に3design-ui内で抑え込めるというか、壊れた時にわかりやすいってのも1つの手ですね 🤔 試しにやってみますか 💪

2022-05-24 12:41 UTC, O-natsu commented on src/chip/Chip.tsx
> +              ${tw`opacity-70`}
@Qs-F こちらとpropsのoverrideの件対応しました！お手すきでご確認お願いします〜〜〜 🙏

2022-05-24 12:43 UTC, O-natsu commented on src/chip/Chip.tsx
> +            ${isEndIcon && tw`flex-row-reverse`}
末尾にアイコンつけたい場合

2022-05-24 12:44 UTC, O-natsu commented on src/chip/Chip.tsx
> +          ${tw`bg-negative-light-default hover:bg-negative-light-hover`};
Chip自体にhoverしたときの実装が漏れてたので対応してます 🙏

2022-05-25 11:49 UTC, Qs-F approved these changes
デザインとプロパティについて自分はこれで大丈夫です！iconのhoverカラーの部分よしなにやってもらってありがとうございます 🙇 (デザイン側で修正しなきゃなところもあるので、追いついたら変更入れます 🙇 )

commit入れてしまったので、review requestしておくので書き方に問題があったらガッツリ修正してもらえますと嬉しいです

2022-05-26 06:22 UTC, O-natsu commented
@Qs-F こちらこそ修正ありがとうございます！大丈夫そうです ✨

2022-05-27 05:32 UTC, merged