feat: Tab 実装
3-shake/3design-ui pull request #714
Opened 2022-08-08 08:09 UTC by locona

### preview

- 

### 実装内容

### 相談内容(あれば)

2022-08-08 12:48 UTC, Qs-F requested changes
> borderがおかしかったので、修正しました。
変更方法としてはborder ではなく、width/height のデザインに変更したのですが、
そうなるとborder-xxxx ではなく、bg-xxxxx になるので、borderのカラーが変わってしまうのですが、
どうしましょう？

についてですが、スタイル的にはbgでも色の意味としてはborderとして使ってるので、

- `h-0` を指定
- `border-bottom: ${1px または 2px} solid ${それぞれの色}`

でどうでしょうか、手元では問題なく動いている気がします 🙇

2022-08-08 12:48 UTC, Qs-F commented on src/tab/TabList.tsx
>    color?: 'primary' | 'secondary' | 'shade'
shadeのtabはデザイン側では定義してないんですが、使いますか？

2022-08-08 12:48 UTC, Qs-F commented on src/tab/Tab.tsx
> +        root: clsx([`min-w-[${minWidth}] text-primary-medium-default`]),
フォントサイズとboldとpaddingの設定をお願いします！

```suggestion
        root: clsx([`min-w-[${minWidth}] min-h-[auto] text-primary-medium-default text-r font-bold font-sans pt-2 pb-2.5`]),
```

2022-08-08 12:48 UTC, Qs-F commented on src/tab/Tabs.tsx
> +      classes={{
min-heightの設定の修正をお願いします

```suggestion
      classes={{
        root: clsx(['min-h-[auto]']),
```

2022-08-09 05:08 UTC, locona commented on src/tab/TabList.tsx
>    color?: 'primary' | 'secondary' | 'shade'
不要なので削除しておきますね！

2022-08-09 07:40 UTC, locona commented
@Qs-F 
https://github.com/3-shake/3design-ui/pull/714/commits/52847dbde066fcc63f82a20505876fc8634dbb9f

こちらでborder 使うように変更しました！

2022-08-12 08:17 UTC, Qs-F approved these changes
確認しました！ありがとうございます〜！

2022-08-12 09:09 UTC, merged