feat: Vite ライブラリー配布設定
3-shake/3design-ui pull request #719
Opened 2022-08-10 05:09 UTC by locona

https://github.com/3-shake/3design-ui/issues/664

### 実装内容
yalc publish

**開発するアプリケーション**
`yalc add @3-shake/3design-ui`

### 相談内容(あれば)

2022-08-12 10:07 UTC, Qs-F requested changes
他のところでimportするとclassにtailwindのutility classが設定されていることを確認しました！そこから先 (tailwindcssを設定して使えるか) は確認してませんが、一旦大丈夫そうでした！ありがとうございます 🙇 

細かいところだけコメント入れました

2022-08-12 10:07 UTC, Qs-F commented on vite.config.ts
> +          sourcemap: true,
sourcemapはできればproductionでは消したい気がするので、 https://github.com/Qs-F/fkit/blob/db70e65a1e5869129eff55fe696e35584d51466b/vite.code.config.ts#L24 こういう感じで対応をお願いしたいです

2022-08-15 11:00 UTC, locona commented on vite.config.ts
> +          globals: {
そうだったんですね！
ありがとうございます！

2022-08-15 11:08 UTC, locona commented
@Qs-F 
レビューありがとうございます！

https://github.com/3-shake/3design-ui/pull/719/commits/af3ac95b63c0a6c1b23b3021899098cb7036d696

こちらで修正いたしました :bow:

2022-08-15 11:36 UTC, Qs-F approved these changes
ありがとうございます、LGTMです 🙇

2022-08-15 11:42 UTC, merged