feat: Table 実装
3-shake/3design-ui pull request #723
Opened 2022-08-16 04:46 UTC by locona

https://github.com/3-shake/3design-ui/issues/688

### 実装内容

### 相談内容(あれば)

2022-08-17 11:23 UTC, Qs-F requested changes
borderの色だけであとは大丈夫そうです！

Scrollerの例、v2ではheaderをfixedにしてたっぽいですがそれは意図的にはずしたであってますか？

2022-08-17 11:23 UTC, Qs-F commented on src/table/Table.tsx
> +          'border-b border-shade-medium-default transition duration-300 ease-in-out hover:bg-shade-light-default',
ここはlightです！
```suggestion
          'border-b border-shade-light-default transition duration-300 ease-in-out hover:bg-shade-light-default',
```

2022-08-18 07:22 UTC, locona commented
@Qs-F 
https://github.com/3-shake/3design-ui/pull/723/commits/54f574813a33f7c435156ac96e96f62c1155b44b#diff-b63cc1d680b7dadb966abac3b31f61e08e9eb1c03dfb910be3770648d42af541R11

こちらで対応しました

2022-08-18 08:09 UTC, Qs-F requested changes
https://github.com/3-shake/3design-ui/blob/999dff025f2e89b48388d55ae1f45ca6aa52b081/src/table/Table.tsx#L190

すみません、ここも `border-shade-light-default` でお願いします！あと `tr` につけているためかスクロールしたときに線も上に行ってしまうので、固定したいです！

2022-08-18 09:58 UTC, Qs-F approved these changes
完璧です！ありがとうございます！ (`border-separate` なんてものがあるんですね… すごい…)

2022-08-18 10:05 UTC, merged